const data = {
  products: [
    {
      _id: '1',
      name: 'Samsung S22 Ultra',
      slug: 'samsung-s22-ultra',
      category: 'Phones',
      image: '/images/samsungs22ultra.jpg',
      price: 990,
      countInStock: 10,
      brand: 'Samsung',
      numReviews: 10,
      description: '2022 Samsung Flagship',
    },
    {
      _id: '2',
      name: 'iPhone 14 Pro Max',
      slug: 'iphone-14-pro-max',
      category: 'Phones',
      image: '/images/iphone14promax.jpg',
      price: 1190,
      countInStock: 15,
      brand: 'Apple',
      numReviews: 10,
      description: '2022 Apple Flagship',
    },
    {
      _id: '3',
      name: 'Google Pixel 5 Pro',
      slug: 'google-pixel-5pro',
      category: 'Phones',
      image: '/images/googlepixel5pro.jpg',
      price: 800,
      countInStock: 10,
      brand: 'Google',
      numReviews: 10,
      description: '2022 Google Flagship',
    },
    {
      _id: '4',
      name: 'Motorola Razr 5G 2020',
      slug: 'motorola-razr-5g-2020',
      category: 'Phones',
      image: '/images/motorazr2020.jpg',
      price: 790,
      countInStock: 20,
      brand: 'Motorola',
      numReviews: 30,
      description: '2020 Samsung Flagship',
    },
    {
      name: 'Vivo X Note 5G',
      slug: 'Vivo X Note 5G',
      category: 'Phones',
      image: '/images/Vivo X Note 5G.jpg',
      price: 999.99,
      countInStock: 0,
      brand: 'Vivo',
      numReviews: 70,
      description: '2022 Vivo Flagship',
    },
    {
      name: 'Oppo Reno7 Z 5G Cosmic Black',
      slug: 'Oppo Reno7 Z 5G Cosmic Black',
      category: 'Phones',
      image: '/images/Oppo Reno7 Z 5G Cosmic Black.jpg',
      price: 465.99,
      countInStock: 0,
      brand: 'Oppo',
      numReviews: 70,
      description: '2022 Oppo Flagship',
    },
    {
      name: 'NUBIA RED MAGIC 7S PRO SILVER MERCURY',
      slug: 'NUBIA RED MAGIC 7S PRO SILVER MERCURY',
      category: 'Phones',
      image: '/images/nubia-red-magic-7s-pro-18gb1tb-transparent-silver-mercury.jpg',
      price: 1105.99,
      countInStock: 0,
      brand: 'Nubia',
      numReviews: 70,
      description: '2022 Nubia Flagship',
    },
    {
      name: 'Xiaomi Mi 12 Pro',
      slug: 'Xiaomi Mi 12 Pro',
      category: 'Phones',
      image: '/images/xiaomi-mi-12-pro.jpg',
      price: 999.99,
      countInStock: 1,
      brand: 'Xiaomi',
      numReviews: 30,
      description: '2022 Xiaomi Flagship',
    },
    {
      name: 'Asus ROG Phone 6',
      slug: 'Asus ROG Phone 6',
      category: 'Phones',
      image: '/images/asus rog phone 6.jpg',
      price: 1499.99,
      countInStock: 0,
      brand: 'Asus',
      numReviews: 70,
      description: '2022 Asus Flagship',
    },
    {
      name: 'Oppo Reno8',
      slug: 'Oppo Reno8',
      category: 'Phones',
      image: '/images/oppo-reno-8-8gb128gb-gold.jpg',
      price: 1009.99,
      countInStock: 23,
      brand: 'Oppo',
      numReviews: 70,
      description: '2022 Oppo Flagship',
    },
    {
      name: 'Motorola Razr 2022 Fold',
      slug: 'Motorola Razr 2022 Fold',
      category: 'Phones',
      image: '/images/Motorola Razr 2022 Fold.jpg',
      price: 1009.99,
      countInStock: 50,
      brand: 'Motorola',
      numReviews: 70,
      description: '2022 Motorola Flagship',
    },
    {
      name: 'Realme GT Neo 3',
      slug: 'Realme GT Neo 3',
      category: 'Phones',
      image: '/images/realme-gt-neo-3-12gb256gb-white-80w-charging.jpg',
      price: 999.99,
      countInStock: 1,
      brand: 'Xiaomi',
      numReviews: 30,
      description: '2022 Xiaomi Flagship',
    },
  ],
};

export default data;
